Tarefa 01 - Git e GitHub com Markdown - Lucas Mateus da Silva
tacianosilva/eng-software-2 pull request #266
Opened 2024-03-16 23:11 UTC by mts-lucas

closes #261

2024-08-12 19:43 UTC, tacianosilva requested changes
@mts-lucas Modificou arquivo README do diretório tarefas/20241 (não deve modificar esse arquivo). Colocou o arquivo tarefa01.md na raiz tarefas/20241, deveria estar no seu diretório, além disso a tarefa que aparece é de @CharlesEdu07.

2024-08-12 19:43 UTC, tacianosilva commented on tarefas/20241/tarefa01.md
> -### Descrição:
@mts-lucas  Arquivo da tarefa 01 de @CharlesEdu07  no diretório raiz. Não vi sua tarefa 01.

2024-08-12 21:45 UTC, CharlesEdu07 commented
Não entendi, meus arquivos estão todos dentro da pasta com meu nick

[image: image.png]

Em seg., 12 de ago. de 2024 às 16:44, Taciano Morais Silva <
***@***.***> escreveu:

> ***@***.**** requested changes on this pull request.
>
> @mts-lucas <https://github.com/mts-lucas> Modificou arquivo README do
> diretório tarefas/20241 (não deve modificar esse arquivo). Colocou o
> arquivo tarefa01.md na raiz tarefas/20241, deveria estar no seu diretório,
> além disso a tarefa que aparece é de @CharlesEdu07
> <https://github.com/CharlesEdu07>.
> ------------------------------
>
> In tarefas/20241/tarefa01.md
> <https://github.com/tacianosilva/eng-software-2/pull/266#discussion_r1714285079>
> :
>
> > -*Nome:* Charles Eduardo Araújo de Faria
> -*Usuário GitHub:* https://github.com/CharlesEdu07
> -*E-mail:* ***@***.***
> -
> ----
> -
> -## Projeto: SigEstoque
> -
> -### Descrição:
>
> @mts-lucas <https://github.com/mts-lucas> Arquivo da tarefa 01 de
> @CharlesEdu07 <https://github.com/CharlesEdu07> no diretório raiz. Não vi
> sua tarefa 01.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tacianosilva/eng-software-2/pull/266#pullrequestreview-2233879002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMPP5SZOMNBJWNRUKNIF7IDZREGADAVCNFSM6AAAAABLI4MZNWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMZTHA3TSMBQGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-13 23:34 UTC, mts-lucas commented on tarefas/20241/tarefa01.md
> -### Descrição:
Acho que fiz alguma besteira quando solicitei o pull, perdi toda a minha tarefa

2024-08-13 23:49 UTC, mts-lucas commented
Corrigi o problema, aparentemente quando fui solicitar o pull mechi onde não devia e peguei o trabalho de charles por engano

2024-08-30 15:53 UTC, tacianosilva approved these changes

2024-08-30 15:54 UTC, closed without merging